### ISSUE TITLE
Logos in text areas overlap writing area

### ISSUE THREAD

**Issue by maderlock** [checkout/checkout-magento2-plugin#10]
![screenshot 2017-10-03 10 27 58](https://user-images.githubusercontent.com/630320/31118524-9686540a-a825-11e7-9ada-179395ea31fd.png)

It's possible to enter the CVV digits, and the info hover also works, but they overlap which looks a bit broken. Similarly, the card number disappears underneath the card type logo.

Is it possible to make the boxes longer to avoid the overlap?

**Comment by nicolas-maalouf-cko** [comment]
@maderlock this is an expected behaviour of the iframe as it's responsive.
Do you use a particularly narrow design that makes the payment form squeeze? 

Thanks

**Comment by maderlock** [comment]
Ah, I see. We do have a slightly narrower section for the form, as otherwise other payment options are rather spread out. The issue we have is the 50% width from the checkout.com module. Here is the css that forces the form to be displayed at 50% of the available width from checkoutcom/magento2/view/adminhtml/templates/embedded.phtml:

        #cko-form-holder {
	    max-width: 50%;
	}

The restriction I assume is to avoid overly large text boxes. I would suggest instead giving a pixel maximum e.g.

       #cko-form-holder {
	    max-width: 400px;
	}

Although this might seem more restrictive, what this actually allows is the form to be more responsive with fewer rules - it can fill the space available up to a certain size. But no further. Restricting by a percentage will only work in certain circumstances and actually looks very squeezed on mobiles.

**Comment by maderlock** [comment]
Ah - it's in two files:
checkoutcom/magento2/view/adminhtml/templates/embedded.phtml:
checkoutcom/magento2/view/frontend/templates/embedded.phtml:

**Comment by nicolas-maalouf-cko** [comment]
@maderlock 

We would prefer not to use a fixed width because it breaks the fluid design on larger widths.

Would you be able to try max-width: 60% and see if it looks good on your end?
It seems to cater for the edge cases on our side.

**Comment by maderlock** [comment]
Do you see my point about how your percentage design is less fluid than a hard limit? Think of it as allowing the element to fill space fluidly with a limit to stop it getting too big and looking odd.  To allow for larger widths does a percentage make sense? I don't think so, because the point at which the form elements start looking strange is absolute not percentage.

If you are concerned that this seems to fixed, you might want to make your maximum in ems, as this will then allow you to restrict the maximum size of the elements based on how stretched they are given the current text size.

The problem with a percentage is that when you have a smaller space, anything less than 100% is going to look wrong. You can change this by media-query for smaller screens, but that means that you will have a threshold of change that will be hard-coded in pixels anyway! You cannot get away from some form of limit.

**Comment by nicolas-maalouf-cko** [comment]
@maderlock we will be adding media-query to the default CSS, thanks for the suggestion.

As you appear to be using an non-usual format in your Magento theme, we offer the possibility to update a custom CSS to handle the embedded form according to your design needs.
You can do that in the plugin configuration.

Please have a look at [this](https://docs.checkout.com/getting-started/checkout-js-v2/embedded) page that explains a bit more how the custom CSS works for the embedded form.

**Comment by maderlock** [comment]
If you take my advice then you won't need to use a media query - much better fluid design :) But I see that we're not going to agree on this one, so we'll use custom css.
