### ISSUE TITLE
Config loader refactoring

### ISSUE THREAD

**Issue by david-fiaty** [checkout/checkout-magento2-plugin#101]
https://github.com/checkout/checkout-magento2-plugin/blob/f91ddba78ecac0e963cc74ec2351be01f0268369/Gateway/Config/Config.php#L83

The getEnabledMethods() is inherited from the \Magento\Payment\Gateway\Config\Config class and will get the payment methods enabled on a website level.

It will not check which internal Checkout.com payment methods are enabled. The result is that the payment methods will never show on a new install.

**Comment by david-fiaty-cko** [comment]
More globally, the config provider will need optimisation. We will:
1- load the config.xml file with xml parser
2- loop through each value in the xml file and retrieve the db value
3- Send a merged array of xml and db values to the config provider

**Comment by david-fiaty-cko** [comment]
issue fixed merging upa-config-loader branch into upa branch:
https://github.com/checkout/checkout-magento2-plugin/commit/cd5dce13fe3aeb2a9264e824c5474ef80ff462aa
