### ISSUE TITLE
Frames JS error

### ISSUE THREAD

**Issue by joe-vortex** [checkout/checkout-magento2-plugin#120]
From a default setup, going to Stored Payment Methods in the customer account area, an error is thrown - `Uncaught ReferenceError: Frames is not defined` - looking in `vault_cards_listaction.xml` there is a script tag - `<script src="CheckoutCom_Magento2/js/collapseForm.js"/>` which relies on a window variable `Frames`.

Suggestion would be to:
- remove `<script src="CheckoutCom_Magento2/js/collapseForm.js"/>` from `vault_cards_listaction.xml` 
- add the following to `vendor/checkoutcom/magento2/view/frontend/templates/add-new-card-form.phtml`:
```
<script type="text/x-magento-init">
    {
        "*": {
            "framesjs": {},
            "collapseForm": {}
        }
    }
</script>
```
- add the following to `vendor/checkoutcom/magento2/view/frontend/requirejs-config.js`:
```            
framesjs: 'https://cdn.checkout.com/js/frames.js',
collapseForm: 'CheckoutCom_Magento2/js/collapseForm'
```

This removes the collapse form js from render blocking and utilises standard magento requirejs loading.

**Comment by david-fiaty-cko** [comment]
@joe-vortex thanks from your message. We haven't managed to reproduce this error on a default setup. Please check the screenshot below to see that the console is clean and Frames displaying properly.
Could you please provide more information on your specific context and/or on how to reproduce this?

<img width="1424" alt="frames-integration" src="https://user-images.githubusercontent.com/26484662/57706849-6da45380-765e-11e9-8001-bc52ff81db1e.png">

**Comment by joe-vortex** [comment]
Hey @david-fiaty-cko, my apologies, I found there was an override in my theme, preventing the embedded url from showing outside the checkout. It works without that override. However I would still point out that for performance purposes my PR should still be considered so that the script is not render blocking. including script tags in a template is not in keeping with magento best practices.

**Comment by david-fiaty-cko** [comment]
@joe-vortex, thanks for your message. We are working on a new version of the module that will consider your observations.

The current release is stable. It's preferable not to add changes not addressing an issue that will require additional testing and maybe impact other merchants. Thank you.

**Comment by joe-vortex** [comment]
sure, thanks for taking the time to consider my suggestion.
