### ISSUE TITLE
Large gap under integrated form

### ISSUE THREAD

**Issue by maderlock** [checkout/checkout-magento2-plugin#13]
Before the commit button there is a very large gap. I know why this is there - so that the tool tips in the iframe have space to be shown - a fix from a previous issue.

Not sure what the answer is there - if you move the button up then either it has to be over the iframe, which means that the tooltip will go underneath it; or it goes under the iframe, which means that the button cannot be pressed.

Our workaround may be to move the button up and over the iframe, but shift it to the left so that it does not interfere with the tool tip.

I'll have to leave it to you to see if you can come up with a general solution - perhaps the tool-tip needs to open upwards?

![screenshot 2017-10-13 14 18 22](https://user-images.githubusercontent.com/630320/31548636-62b0f5e4-b023-11e7-9b1f-10da9d0a4f12.png)

**Comment by david-fiaty-cko** [comment]
The CSS min-height constraint has been removed in version 1.0.9.

**Comment by maderlock** [comment]
And this still allows for the tool-tip on the CVV to be seen? That's why this was increased before.

**Comment by maderlock** [comment]
I see the tool tip has been removed.

I still have a large gap, because the iframe is set to 100% height. If I remove this then it looks fine, but the css is added in https://cdn.checkout.com/v2/js/css/checkout-2.0.8.css line for iframe.cko-iframe

**Comment by david-fiaty-cko** [comment]
The 100% height you see doesn't come from the Checkout.com Magento extension, but from the Embedded Form hosted on Checkout's servers. As we cannot change this from a M2 installation, your request about 100% will be transmitted and taken in account for the next release of the Embedded Form, which will be called Frames. 

Please bear with us until the next release is available. It should arrive by next week. In the meanwhile, the property is easy to override and 1 line of code should suffice to tackle the issue.
