### ISSUE TITLE
mage2pro/core module breaking dependency injection of other modules

### ISSUE THREAD

**Issue by nicolas-maalouf-cko** [checkout/checkout-magento2-plugin#14]
@mage2pro 
When setting mode to production DI preferences conflicts are appearing making modules unusable.

Example is when integratning BlueFoot CMS

**Comment by mage2pro** [comment]
Publish exact error message instead of generic words.

**Comment by redboxmarcins** [comment]
While using Magento 2.0.10 EE there is a problem that mage2pro/core and magento2/checkout.com modules are prevening some modules to set preferences in di.xml

example one:
`<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Store\Controller\Store\SwitchAction"
                type="Boutique1\StoreSwitcher\Controller\Store\SwitchStoreAction"/>
    
    <preference for="Boutique1\StoreSwitcher\Api\ShippingCookieManagerInterface"
                type="Boutique1\StoreSwitcher\Model\ShippingCookieManager" />
</config>`


example 2:
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Framework\Data\Form\Element\Editor" type="Gene\BlueFoot\Block\Element\Editor" />
    <preference for="Gene\BlueFoot\Model\Config\ConfigInterface" type="Gene\BlueFoot\Model\Config" />

    <preference for="Gene\BlueFoot\Api\Data\EntityInterface" type="Gene\BlueFoot\Model\Entity" />
    <preference for="Gene\BlueFoot\Api\Data\EntitySearchResultsInterface" type="Magento\Framework\Api\SearchResults" />
    <preference for="Gene\BlueFoot\Api\EntityRepositoryInterface" type="Gene\BlueFoot\Model\EntityRepository" />

    <preference for="Gene\BlueFoot\Api\Data\ContentBlockInterface" type="Gene\BlueFoot\Model\Attribute\ContentBlock" />
    <preference for="Gene\BlueFoot\Api\Data\ContentBlockSearchResultsInterface" type="Magento\Framework\Api\SearchResults" />
    <preference for="Gene\BlueFoot\Api\ContentBlockRepositoryInterface" type="Gene\BlueFoot\Model\Attribute\ContentBlockRepository" />

    <preference for="Gene\BlueFoot\Api\Data\ContentBlockGroupInterface" type="Gene\BlueFoot\Model\Attribute\ContentBlock\Group" />
    <preference for="Gene\BlueFoot\Api\Data\ContentBlockGroupSearchResultsInterface" type="Magento\Framework\Api\SearchResults" />
    <preference for="Gene\BlueFoot\Api\ContentBlockGroupRepositoryInterface" type="Gene\BlueFoot\Model\Attribute\ContentBlock\GroupRepository" />

    <type name="Magento\Eav\Model\Entity\Setup\PropertyMapper\Composite">
        <arguments>
            <argument name="propertyMappers" xsi:type="array">
                <item name="bluefoot" xsi:type="string">Gene\BlueFoot\Model\ResourceModel\Setup\PropertyMapper</item>
            </argument>
        </arguments>
    </type>

    <type name="Magento\Eav\Model\Entity\AttributeCache">
        <arguments>
            <argument name="unsupportedTypes" xsi:type="array">
                <item name="gene_bluefoot_entity" xsi:type="string">gene_bluefoot_entity</item>
            </argument>
        </arguments>
    </type>
</config>
```

In that case when creating new instance of that class original class is returned not preferenced one

This only happens when site is in production mode

Please use Magento EE 2.0.10 which was installed via composer metapackage (so all files are in vendor)

Steps to reproduce:
```
rm -rf vendor/*
composer update
composer require magento2/checkout.com:*
php bin/magento setup:upgrade
rm -rf var/di var/generation/ var/cache/ 
php bin/magento deploy:mode:set production 
rm -rf var/di var/generation/ var/cache/ 
bin/magento setup:di:compile  
php bin/magento c:fl 
php bin/magento c:cl 
php bin/magento s:up --keep-generated
```


After removing module or switching to developer mode everything works as expected

Please advice

**Comment by mage2pro** [comment]
As I know, you are using an outdated [`1.4.28`](https://github.com/mage2pro/core/releases/tag/1.4.28) version of the `mage2pro/core` package and a custom [`dev-savecards`](https://github.com/CKOTech/checkout-magento2-plugin/tree/dev-savecards) branch of the Checkout.com extension.   
I do not support nor mage2pro/core 1.4.28 (the current version is [1.8.8](https://github.com/mage2pro/core/releases/tag/1.8.8)) nor `dev-savecards` branch.

**Comment by redboxmarcins** [comment]
1.8.8 does the same thing

**Comment by mage2pro** [comment]
Do you use the `1.1.3` Checkout.com extension version?

**Comment by nicolas-maalouf-cko** [comment]
Yes same happens when using everything from master branch.
(Checkout.com 1.1.3 and mage2pro/core 1.8.8)

**Comment by mage2pro** [comment]
> rm -rf vendor/*
composer update
composer require magento2/checkout.com:*
php bin/magento setup:upgrade
rm -rf var/di var/generation/ var/cache/ 
php bin/magento deploy:mode:set production 
rm -rf var/di var/generation/ var/cache/ 
bin/magento setup:di:compile  
php bin/magento c:fl 
php bin/magento c:cl 
php bin/magento s:up --keep-generated

I do not understand these "steps to reproduce". 
What should I see after this commands?

**Comment by redboxmarcins** [comment]
If you have any other modules in vendor which set preferences - you will see in var/di that it is not there
and also if you try to create object - it will not honour it

**Comment by mage2pro** [comment]
What exact module should I install and check?  
I do not have BlueFoot CMS, so I can not check it.

**Comment by dmitry-fedyuk** [comment]
Closed because of absence of response.
