### ISSUE TITLE
«Access level to Dfe\CheckoutCom\Method::amountFactor() must be protected (as in class Df\Payment\Method) or weaker»

### ISSUE THREAD

**Issue by Kamrog** [checkout/checkout-magento2-plugin#15]
Hi I am getting this error when running setup:upgrade after configuring composer:

> PHP Fatal error:  Access level to Dfe\CheckoutCom\Method::amountFactor() must be protected (as in class Df\Payment\Method) or weaker in /usr/share/nginx/html/magento_folder/vendor/magento2/checkout.com/Method.php on line 21

Changing
`private function amountFactor() {return dfc($this, function() {`
Into `protected function amountFactor() {return dfc($this, function() {`
on line 399 in /vendor/magento2/checkout.com/Method.php solves the problem

**Comment by dmitry-fedyuk** [comment]
You are doing something wrong: the `Dfe\CheckoutCom\Method` class from the latest [`1.1.10`](https://github.com/checkout/checkout-magento2-plugin/tree/1.1.10) release does not have the `amountFactor` method at all: https://github.com/checkout/checkout-magento2-plugin/blob/1.1.10/Method.php

**Comment by Kamrog** [comment]
Just followed composer install instructions :)

**Comment by dmitry-fedyuk** [comment]
I noticed the same problem [with another client](https://mage2.pro/t/topic/2388), and I think you both have ignored (or have a failure) with the step 1 of the upgrade instruction:

```
composer self-update && composer update --prefer-source
```

In any case when your are unable to follow a step of an official instruction, it is better to report it, when to ignore the step and break your site.
