### ISSUE TITLE
Vault title cannot be modified

### ISSUE THREAD

**Issue by maderlock** [checkout/checkout-magento2-plugin#15]
There seems to be an area in the system config where the vault title can be specified:
![screenshot 2017-10-13 16 00 15](https://user-images.githubusercontent.com/630320/31552558-bd8aa206-b02f-11e7-8987-71e81d4beafc.png)

However, the frontend always just shows this under the title checkout.com:
![screenshot 2017-10-13 16 00 34](https://user-images.githubusercontent.com/630320/31552590-d00ca79e-b02f-11e7-91fa-d25110efb7d4.png)

I cannot find any reference in the code to vault_title outside system.xml, so I suspect this has not been connected up? That or I don't understand what this title is for, which is possible.

**Comment by david-fiaty-cko** [comment]
issue fixed in new version 1.0.8

**Comment by maderlock** [comment]
I installed 1.0.8, cleared cache, varnish, static content etc. and put through an order with a card for storage. This is what I now see:

![screenshot 2017-10-16 17 04 58](https://user-images.githubusercontent.com/630320/31622502-7f90900c-b294-11e7-8770-43bc4698f610.png)

Here is a javascript error in the console:

<img width="816" alt="screenshot 2017-10-16 17 10 51" src="https://user-images.githubusercontent.com/630320/31622712-13f8cafc-b295-11e7-8bbb-0e5289f2f466.png">

**Comment by david-fiaty-cko** [comment]
I haven't managed to reproduce this issue. The js error in the console says that getVaultTitle() is not defined. The getVaultTitle() function has been added to fix the vault title issue and should be present in your install.

Please check the following file to make sure the function exists:
/view/frontend/web/js/view/payment/method-renderer/vault.js

You should see the function on line 24.
Also, please try a complete rebuild of the install with the following command:

`rm -rf var/cache var/generation/ var/di && php bin/magento setup:upgrade && php bin/magento setup:di:compile && php bin/magento cache:clean && chmod 777 var/ && php bin/magento setup:static-content:deploy && chown www-data:www-data . -R
`

For now I have the feeling that either the updated vault.js file is not on your install, or the install is still using old versions of the file.

**Comment by maderlock** [comment]
I can now see the changes. I had done as you suggested, but it would appear that even with a force refresh of the page in the browser, the javascript was browser cached so none of those steps made a difference until I manually cleared my browser cache of all files.

This would not have been a problem in our production environment as we use version numbers in the path, as is pretty commonly done to avoid these issues.
