### ISSUE TITLE
The latest upgrade does not work with Javascript minification enabled

### ISSUE THREAD

**Issue by parekhreena** [checkout/checkout-magento2-plugin#164]
The checkout page fails to load with below error: 
`[2019-07-03 03:04:59] [ERROR] Failed to load the "CheckoutCom_Magento2/js/view/payment/method-renderer/checkoutcom_card_payment" component.`

This happens when Javascript minification and bundling is enabled.

**Comment by david-fiaty** [comment]
@parekhreena, could you please specify how you enable minification and bundling?

**Comment by parekhreena** [comment]
@david-fiaty We are Using Standard Magento steps: https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/js-bundling.html

**Comment by david-fiaty-cko** [comment]
The following URL has been made available for the Frames integration: https://cdn.checkout.com/js/frames.min.js​
You should now be able to run minified/bundled installations without issues.
Please reopen if needed.
