### ISSUE TITLE
Incorrect Callback URL in store view

### ISSUE THREAD

**Issue by parekhreena** [checkout/checkout-magento2-plugin#165]
The callback URL field in Admin > Stores > Configuration which gets auto-populated always takes the default store value. It should take the value based on the callback URL set against account keys which are at store view level. So for instance if default store callback URL is www.example.com/checkout/success
and store view level callback URL is www.example.com/ae_en/checkout/success , in this case in Admin panel > Stores > Configuration > Change Store view to ae_en > Sales > Payment Methods > Checkout.com > Callback URL will still show www.example.com/checkout/success

**Comment by david-fiaty-cko** [comment]
Hi @parekhreena, this field is just informative and the value is not actually used.
In the payment request, the value that is used is the one of the current store. 

This is done dynamically and the value of the field you are looking at is never used. The use of this field was deprecated in previous versions and doesn't exist in the latest versions of the module.

Please upgrade to the latest version.
