### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getPayment() on null 

### ISSUE THREAD

**Issue by kaushalsutharoc** [checkout/checkout-magento2-plugin#174]
PHP Fatal error:  Uncaught Error: Call to a member function getPayment() on null in vendor/checkoutcom/magento2/Helper/Utilities.php:94

Magento ver: Magento 2.2.5
Checkout.com module version : 2.0.5

When I try to place order with Product which has only 1 Qty available.

I traced error and found at  vendor/magento/module-quote/Model/QuoteManagement.php: 522

It throwing an error of Product is out of stock.

And in this file : vendor/checkoutcom/magento2/Controller/Payment/Verify.php : 139 

Order object is null.

**Comment by david-fiaty-cko** [comment]
@kaushalsutharoc, thank you for the feedback. Do you have anything in var/log/checkoutcom_magento2.log, var/log/system.log, var/log/exception.log or var/log/debug.log related to this error?

**Comment by kaushalsutharoc** [comment]
var/log/checkoutcom_magento2.log
INFO (6): This product is out of stock.

**Comment by david-fiaty-cko** [comment]
@kaushalsutharoc, do you get any duplicate orders, when this issue happens?

**Comment by kaushalsutharoc** [comment]
@david-fiaty-cko yes we do get duplicate orders.

**Comment by david-fiaty-cko** [comment]
@kaushalsutharoc, the duplicate order issue is a core bug that has been reported on Magento’s GitHub repository on version 2.2.

The bug has been acknowledged by the core team but seems to be still present on 2.3 series:
https://github.com/magento/magento2/issues/13952

We are investigating solutions to overcome this core issue, I will let you know as soon as we have a viable workaround.

**Comment by kaushalsutharoc** [comment]
Okay, Thanks @david-fiaty-cko. 

I've more one question if you don't mind.

When we do partial refund from Magneto backend, (Order > Invoice > View Invoice > Credit Memo > Refund)

Suppose if there are two items and I refund 1 item only then it works as expected but invoice status change to cancel so now I can't refund remaining item in this case. 

Thanks.

**Comment by fmjrey** [comment]
Also as I explained in https://github.com/magento/magento2/issues/13952#issuecomment-530102166 there may be a case where duplicate orders are created even with a non null payment.

**Comment by david-fiaty-cko** [comment]
@kaushalsutharoc we haven't been able to reproduce this. If however you're still having the issue with the latest version 2.0.6, please open a separate issue of this additional question.
