### ISSUE TITLE
After enabling live payments with 3DS enabled - success page does not get shown. This only happens with live payments and not on sandbox. 

### ISSUE THREAD

**Issue by parekhreena** [checkout/checkout-magento2-plugin#175]
Hi,

We switched from test environment to live environment. The setting is Authorize only in magento and 3DS is enabled. After customer places an order, they are redirected to bank website where they are charged successfully and then back to magento. the transaction in checkout.com shows as Authorized only, but customer receives a message from bank that amount was captured and when customer is redirected back to magento they do not get the order success page or order number details and order gets placed in magento. This is only happening with Live account, we are not experiencing this with sandbox account. The URLs configured in checkout.com for payment verification and failure are correct, so are all the keys. 
Please advice on this issue.

**Comment by kaushalsutharoc** [comment]
@parekhreena try to check `var/log/checkoutcom_magento2.log` if it may help.

**Comment by david-fiaty-cko** [comment]
@parekhreena we haven't been able to reproduce this issue. Sandbox uses the same request/response data and workflow as live. This looks like a possible misconfiguration fo your account.  Please reopen if the issue persist, with more information if possible.
