### ISSUE TITLE
Version 2.0.9 does not work in production mode

### ISSUE THREAD

**Issue by skynixukraine** [checkout/checkout-magento2-plugin#184]
Steps to reproduce the issue:

1. Enable JS minification, merging & bundling
2. Enable production mode

We can see that the site is broken, when it should load 1 minified, merged and bundled Javascript, it is trying to load non existing regular JS files, see attached screen 
<img width="662" alt="SUNSHINE NUTRITION - Brands 2019-10-16 08-00-29" src="https://user-images.githubusercontent.com/12690168/66889526-79b88680-efeb-11e9-837b-5ac8b2a46ef2.png">

**Comment by david-fiaty-cko** [comment]
@skynixukraine, this is fixed in the latest release 2.0.10
