### ISSUE TITLE
PaymentMethod not showing in frontend checkout page - M2 2.3.3&2.2.8

### ISSUE THREAD

**Issue by a970032** [checkout/checkout-magento2-plugin#185]
![image](https://user-images.githubusercontent.com/18587853/66910634-7b149e00-f041-11e9-9135-cfa69efbdf81.png)
Enabled in backend but payment method is not showing in checkout page please fix this asap my client is using this module to do payment

**Comment by david-fiaty-cko** [comment]
@a970032, payment options show only if they are properly configured and ready to run.
In the case of Apple Pay, please make sure you have provided:

- Public key, private key, private shared key for the Checkout.com account
- Merchant id and certificates for the Apple Pay account
