### ISSUE TITLE
No invoice created even if set to do so

### ISSUE THREAD

**Issue by maderlock** [checkout/checkout-magento2-plugin#21]
Using 1.0.8 with Magento 2.1.9:

Setup:
* Extension in iframe mode (not redirecting).
* Set option to automatically create invoice.

Actions:
* Put through order on frontend

Expected:
* Order created with paid invoice

Actual:
* Order created but no invoice created

**Comment by moneef** [comment]
Hey @maderlock ,

You have to capture the payment before the module create the invoice got to  your `Dashboard -> Transactions` 
select `Transaction ` from the sidebar menu of your `Dashboard `a list of transactions will show up, select the transaction for that order and `check the box` next to it then go to the `action drop-down menu` and select `Capture`, a window will pop-up select `Full Capture` or `Partial Capture`  and click `Capture `now the invoice will be generated 

![1](https://user-images.githubusercontent.com/6404057/32230996-79adff08-be65-11e7-870c-68e7d56c11f8.PNG)
![2](https://user-images.githubusercontent.com/6404057/32230997-79e2a906-be65-11e7-9c93-e83918460938.PNG)

**Comment by nicolas-maalouf-cko** [comment]
@maderlock @moneef 
This will also happen automatically on capture when autocapture is enabled from the plugin configuration.

You also need to make sure the Webhook URL is properly configured in the hub, and that your server is not blocking these webhooks.

**Comment by maderlock** [comment]
Webhook is set to the one shown in the system config setting.
Autocapture is set to yes.
Autoinvoice is set to yes.

There are no callbacks in the server logs except for the test calls I asked checkout.com to send by pressing the Test button in the callback dialog.

So I think this confirms that there is nothing in the server setup stopping callbacks. The URLs I have double-checked and are correct. And the system config options for the module are requesting invoices to be made.

Can you reproduce this? We are using an embedded form.

**Comment by david-fiaty-cko** [comment]
This invoice creation issue has been fixed in the latest release 1.0.12.
