### ISSUE TITLE
how do i find root directory of magento2?

### ISSUE THREAD

**Issue by pradeep51** [checkout/checkout-magento2-plugin#24]

**Comment by nicolas-maalouf-cko** [comment]
Can you please elaborate on this?

**Comment by david-fiaty-cko** [comment]
The root of Magento 2 is the directory where you find the following sub directories:
/app
/bin
/dev
/lib
/phpserver
/pub
/setup
/update
/var
/vendor

Please use the Magento forum for Magento related questions.
