### ISSUE TITLE
The order confirmation email is not sent

### ISSUE THREAD

**Issue by disiri** [checkout/checkout-magento2-plugin#243]
Hi guys,

Seems like the order email is not being sent when I used the checkout.com payment method. Do you guys have any idea? Only happens on order.. invoicing is fine. Currently running magento 2.3.4 and on test account of checkout.com

**Comment by disiri** [comment]
Ok update, when I placed the order.. status is only set to Pending?

**Comment by david-fiaty-cko** [comment]
@disiri, the reason for this is probably that your Webhook URL is incorrect or not provided in the Hub. For more info, please have a look at the last section "Webhook URL" of the readme file.

**Comment by disiri** [comment]
Everything was set accordingly, i had checked it multiple times figuring out what went wrong. Even deleted the hooks and requesting it again but still no luck. See below attachment for my settings on magento and sandbox.

![image](https://user-images.githubusercontent.com/8130617/77574906-27f61f80-6eec-11ea-80ba-eb4588f21114.png)
![image](https://user-images.githubusercontent.com/8130617/77574928-2f1d2d80-6eec-11ea-9652-2020c60f1a58.png)
![image](https://user-images.githubusercontent.com/8130617/77575794-81128300-6eed-11ea-93c0-8a1acaca232a.png)

I am on magento 2.3.4, currently on developer mode.. checkout account was on sandbox too. So basically what I dont understand is why my order status is set to Pending when I clearly set it to "Processing" in my Order setting - and was wondering if the order confirmation not sending is related to that? Because if I trigger "send email" manually from sales/order dashboard it works.

**Comment by disiri** [comment]
Also since I'm on developer mode, I don't need to run the bin/magento setup:di:compile? Right?

**Comment by disiri** [comment]
This fixed by doing setup:di:compile
