### ISSUE TITLE
Set as default payment method

### ISSUE THREAD

**Issue by disiri** [checkout/checkout-magento2-plugin#244]
Is there anyway where I can set this as a default payment method? Mixins seems to be not working. Tried out adding the this.selectPaymentMethod() in the init functions but there are some complications on other functions. 

Please advise.

**Comment by david-fiaty-cko** [comment]
@disiri, setting the order of your payment options should do the trick. Put checkout.com first in the list.

**Comment by disiri** [comment]
I only have checkoutcom payment method, radio button is selected (but the radio button is hidden since only one, not sure if that's magento default functionality) but the payment form/frame is not properly loaded.

**Comment by david-fiaty-cko** [comment]
@disiri this issue should now be fixed in the 2.2.3 RC version:
https://github.com/checkout/checkout-magento2-plugin/tree/2.2.3-candidate

This is in now in active QA. You will be informed as soon as the official release is available but please feel free to test the RC.

**Comment by david-fiaty-cko** [comment]
@disiri, there is a. new release with a fix for this issue:
https://github.com/checkout/checkout-magento2-plugin/releases/tag/2.2.3

**Comment by david-fiaty-cko** [comment]
Closing this issue as it's now fixed in the 2.2.3 release.

**Comment by david-fiaty-cko** [comment]
@disiri, there is a new configuration parameter allowing admins to decide which Checkout.com payment option should be selected by default.
This parameter is available on the module config page in Stores > Configuration > Sales > Payment methods > Checkout.com > Configuration > Global settings > Default active method

<img width="845" alt="Screenshot 2020-04-29 at 21 41 28" src="https://user-images.githubusercontent.com/26484662/80645452-0c3de600-8a63-11ea-8d16-dd56db952ccc.png">

Only the Checkout.com enabled payment options will be displayed in this list.
Selecting the card payment method option here should allow you to enable it by default and make sure the card form is loaded.

The code is available on the master branch of the Checkout.com Magento 2 module. You can just pull the files from there and update the installation manually.
A composer update will not work as the master branch is still 2.2.4 and there is no new release for now. A recompilation of the M2 instance will be required to be able to use this feature.
