### ISSUE TITLE
D:\xampp2\htdocs\Magento2> rm -rf var/cache var/generation/ var/di 'rm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by pradeep51** [checkout/checkout-magento2-plugin#25]

**Comment by nicolas-maalouf-cko** [comment]
Hi, Magento 2's official requirements mention to run it on Linux and not Windows:
http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements-tech.html

What you're receiving is errors running UNIX commands on a Windows terminal.
