### ISSUE TITLE
PaymentMehod not showing in frontend checkout page - M2 2.1.7

### ISSUE THREAD

**Issue by moneef** [checkout/checkout-magento2-plugin#26]
Hey @david-fiaty-cko and @nicolas-maalouf-cko , 

~~i set up the public and secret key and set the module to enable YES, but i cant see the payment method at the checkout page~~

 **My bad it was the currency settings**

![1](https://user-images.githubusercontent.com/6404057/32217829-37372a4e-be3a-11e7-9168-a1be5c5e8ff1.PNG)

**Comment by nicolas-maalouf-cko** [comment]
@moneef yes, we will make sure this is more obvious in the next update
