### ISSUE TITLE
Emails issues

### ISSUE THREAD

**Issue by moneef** [checkout/checkout-magento2-plugin#27]
Hey @nicolas-maalouf-cko  and @david-fiaty-cko ,

thank you guys for your hard work with this extension.

```
Magento 2 : version 2.1.7.
Checkout.com Module version : 1.0.9.
```

i have a strange problem with emails,

after the order is placed i get an order confirmation email even before the 3D Secure Verification page process is completed. and there is extra info the doesn't suppose to be in the email see issue - #14 

![capture](https://user-images.githubusercontent.com/6404057/32225838-d6c4985e-be57-11e7-9178-919aed50bdd7.PNG)

also when i capture the payment the module creates an invoice but doesn't send the email.
the same with refunds the credit memo is created but it doesn't send the email. i have to send them manually

I also have another issue with callback URLs, but i will open another issue to track them separately

> Oct 31, 2017 3:57:05 PM Pending Payment Customer **Notified**
> Oct 31, 2017 4:01:17 PM Invoice #000000009 created Customer **Notified**
> Oct 31, 2017 4:01:18 PM Processing Customer **Notified**
> Oct 31, 2017 4:01:18 PM Processing
> Oct 31, 2017 4:13:35 PM Processing
> Oct 31, 2017 4:13:35 PM Credit memo #000000004 created
> ### Notes for this Order
> Authorized amount of 100 SAR Transaction ID: charge_test_C87F19CF151S74984601
> Comment added Oct 31, 2017 3:57:05 PM
> Captured amount of 100 SAR Transaction ID: charge_test_EC3A69DF151L749847B0
> Comment added Oct 31, 2017 4:01:18 PM
> Captured amount of  100,00 ر.س online. رقم المعاملة: "charge_test_EC3A69DF151L749847B0"
> Comment added Oct 31, 2017 4:01:18 PM
> We refunded  100,00 ر.س online. رقم المعاملة: "charge_test_8E4B49DF151R7498BE96"
> Comment added Oct 31, 2017 4:13:35 PM

**Comment by david-fiaty-cko** [comment]
The invoice issue described here has been fixed in the latest release 1.0.12.
The email issues were already fixed in 1.0.11. It should be all sorted but please reopen if needed.
