### ISSUE TITLE
Class Checkout\Library\ HttpHandler does not exist

### ISSUE THREAD

**Issue by kh-rawasy** [checkout/checkout-magento2-plugin#275]
You received the following error:
Class Checkout\Library\ HttpHandler does not exist

**Comment by david-fiaty-cko** [comment]
@kh-rawasy, it looks like you've installed the Checkout.com Magento 2 module manually. We do not offer support for manual installation as our integration has a dependency on the Checkout.com PHP SDK: https://github.com/checkout/checkout-sdk-php

Please use composer to install the Checkout.com Magento 2 module.
