### ISSUE TITLE
product_price_required Error for Fawry

### ISSUE THREAD

**Issue by emrahuyanik** [checkout/checkout-magento2-plugin#280]
We are using fawry payment method and we faced with that issue for carts which has free shipping.

https://github.com/checkout/checkout-magento2-plugin/blob/5c2c0f60e05c19400c0486e8e787ccd73be00241/Model/Methods/AlternativePaymentMethod.php#L567

When we debug the code, we saw that there is a missing condition when calculationg product rows. It is trying to send free shipping in products row, and checkout_com services returns error like "product_price_required" for 0 product price.

I think it should be like below.

`        if ($shipping->getShippingDescription() && $shipping->getShippingInclTax() > 0) {
`

And its also should be like that for other methods.

**Comment by luke-fenn-cko** [comment]
Hello Emrah,

I hope all is well. 
We have addressed this now and the fix for this is will be available in an a new release of the plugin, version 2.2.7. We hope to release this in the coming weeks.
We really appreciate your patience.

Thank you,
Luke
