### ISSUE TITLE
API - Masked quote_id

### ISSUE THREAD

**Issue by mdanilowicz** [checkout/checkout-magento2-plugin#298]
https://docs.checkout.com/quickstart/integrate/e-commerce-platforms/magento-2/magento-2-storefront-integration

There is no possibility to send the order as a guest because of lack of support for masked quote id.

https://github.com/checkout/checkout-magento2-plugin/blob/master/Controller/Api/v1.php#L239
https://github.com/checkout/checkout-magento2-plugin/blob/master/Controller/Api/v1.php#L210-L212

**Comment by david-fiaty-cko** [comment]
@mdanilowicz, the 2.2.6 release was shipped with support for masked quote id. I'm closing this issue for now, please feel free to reopen if needed.
