### ISSUE TITLE
Apple Pay cart page button broken for virtual/downloadable product orders

### ISSUE THREAD

**Issue by alexryall** [checkout/checkout-magento2-plugin#323]
For an order that contains only virtual/downloadable products that does not require a shipping address or shipping method https://github.com/checkout/checkout-magento2-plugin/blob/master/view/frontend/web/js/view/payment/cart/checkoutcom_applepay_cart.js will error in a number of places as it is assuming a shipping address and shipping method is required. This is the first error that would be encountered but there are more once fixing this one
![Screenshot 2020-08-19 at 17 59 06](https://user-images.githubusercontent.com/8352646/90667231-6a771a80-e246-11ea-9a3e-0d98828a7d83.png)

The Apple Pay popup should not need to ask for a shipping address at all in this situation. Would also be nice if the module added the button to the minicart too!

**Comment by luke-fenn-cko** [comment]
Hello,

We recently released version 2.2.8 of the module which includes many updates to the Apple Pay logic. With further updates coming in version 2.2.9.
Please update your module version and let us know if this fixes the issue.

Thank you,

Luke

**Comment by luke-fenn-cko** [comment]
Closing this issue as there have been no updates and we have released a fix for this issue.
