### ISSUE TITLE
Undefined property: stdClass::$response_code

### ISSUE THREAD

**Issue by daweedco** [checkout/checkout-magento2-plugin#340]
Magento version 2.3.3 
checkout-magento2-plugin version : 2.2.6

error in log : 

{"0":"Notice: Undefined property: stdClass::$response_code in \/web\/vendor\/checkoutcom\/magento2\/Model\/Service\/PaymentErrorHandlerService.php on line 74","1":"<pre>#1 CheckoutCom\\Magento2\\Model\\Service\\PaymentErrorHandlerService->logError() called at [vendor\/checkoutcom\/magento2\/Controller\/Webhook\/Callback.php:167]\n#2 CheckoutCom\\Magento2\\Controller\\Webhook\\Callback->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#3 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#4 CheckoutCom\\Magento2\\Controller\\Webhook\\Callback\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#5 CheckoutCom\\Magento2\\Controller\\Webhook\\Callback\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [app\/code\/Apptrian\/FacebookPixel\/Plugin\/App\/Action\/Context.php:61]\n#6 Apptrian\\FacebookPixel\\Plugin\\App\\Action\\Context->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#7 CheckoutCom\\Magento2\\Controller\\Webhook\\Callback\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [app\/code\/Bss\/ProductStockAlert\/Plugin\/App\/Action\/Context.php:71]\n#8 Bss\\ProductStockAlert\\Plugin\\App\\Action\\Context->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#9 CheckoutCom\\Magento2\\Controller\\Webhook\\Callback\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#10 CheckoutCom\\Magento2\\Controller\\Webhook\\Callback\\Interceptor->___callPlugins() called at [generated\/code\/CheckoutCom\/Magento2\/Controller\/Webhook\/Callback\/Interceptor.php:26]\n#11 CheckoutCom\\Magento2\\Controller\\Webhook\\Callback\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#12 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:98]\n#13 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#14 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#15 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php:94]\n#16 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#17 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:73]\n#18 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#20 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#21 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:137]\n#22 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#23 Magento\\Framework\\App\\Bootstrap->run() called at [index.php:40]\n<\/pre>","url":"\/checkout_com\/webhook\/callback","script_name":"\/index.php"}

**Comment by luke-fenn-cko** [comment]
Hello,

We have recently released version 2.2.8 module with improvements to the PaymentErrorHandlerService.php and a specific fix for this issue.

Please update to the latest version of the module and let me know if this solves your problem. 

Thank you for your patience in waiting for this update.

Many Thanks,

Luke

**Comment by luke-fenn-cko** [comment]
Closing this issue as there has been no update.
