### ISSUE TITLE
v1.0.14 Frames.js issue

### ISSUE THREAD

**Issue by elvinristi** [checkout/checkout-magento2-plugin#35]
## STR
- Install Magento Commerce 2.1.9 with sample data
- Install latest `checkoutcom/magento2` 1.0.14
- Enable to use Integration "Frames" (embedded)
- Using Sandbox account details
- settings in core_config_data: 
![Settings](https://snaps.vaimo.com/elvin.risti/core_config_data-checkoutcom_1FCF5687.png)
- Using following CC test data:
```
    CC: 4242 4242 4242 4242
    MM: 06 YY: 18  CVV: 100
```

## RESULT

Frames.js version 1.0.14 result:
- After placing order `payment-information` gets after some time "cancelled" and redirected back to "checkout/#payment" (like refreshing the page)
- Order is still placed and correct transaction data is attached.
- Chrome console Networking: 
![Settings](https://snaps.vaimo.com/elvin.risti/frames-js_1FCF1650.png)

When downgrading back to 1.0.13 then such issue doesn't exist.

**Comment by david-fiaty-cko** [comment]
issue fixed in 1.0.15
