### ISSUE TITLE
compatibility issue with PHP 7.0 with Console/Webhooks.php line 31

### ISSUE THREAD

**Issue by halitsavafoglu** [checkout/checkout-magento2-plugin#360]
I have an error while using your extension version: 2.2.7 with Magento 2.2.3 and PHP 7.0

PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /vendor/checkoutcom/magento2/Console/Webhooks.php on line 31

your code is:
`private const DATE = 'date';`

while the ability to specify the visibility of class constants was only added in PHP 7.1

so I had to remove the **private** from the line to make things work... but I don't know if that will make any side effects, so please fix it out.

Regards

**Comment by luke-fenn-cko** [comment]
Hello, 

We have made this change in the upcoming version 2.2.9 but this might not release until next month. So, if you were to update to our current version 2.2.8, you would need to remove the 'private' keyword again. However, the change has been through our QA process and it appears that removing the 'private' does not cause any side effects.
Thank you and if you have any questions don't hesitate to ask,

Luke

**Comment by luke-fenn-cko** [comment]
Closing this issue as we have released a fix for this, please update to the latest version.
