### ISSUE TITLE
Exception: Notice: Trying to access array offset on value of type null in checkoutcom/magento2/Helper/Utilities.php on line 79

### ISSUE THREAD

**Issue by Prasannastha** [checkout/checkout-magento2-plugin#424]
Hello,

I got this error while placing the order in test mode.
1 exception(s):
Exception #0 (Exception): Notice: Trying to access array offset on value of type null in /
![checkoutapi_error](https://user-images.githubusercontent.com/69232506/104581762-1ce0cb80-5687-11eb-8072-a733ebc233e7.png)
vendor/checkoutcom/magento2/Helper/Utilities.php on line 79

I am using the CheckoutCom_Magento2 version 2.0.5. I downloaded it via composer.
My magento version is 2.4 and the PHP version is 7.2.

Thank you

**Comment by luke-fenn-cko** [comment]
Hello,

It appears you are running an out of date version of the module, please update to our latest version 2.3.0

Many Thanks,

Luke

**Comment by alitopaloglu** [comment]
I can reproduce this issue on magento v2.4.2 and checkout_com latest version

**Comment by devamitbera** [comment]
The same issue happens to me as well.

**Comment by devamitbera** [comment]
HI  @luke-fenn-cko  and @alitopaloglu 
I am a little bit confuse about  **success_url** and **failure_url**. where these two urls need and why this need for checkout.

Trying to place an order using Rest Guest API and it working but not why **success_url** and **failure_url** need to pass at request payload.


```
{
  "paymentRequest": {
    "payment_token": "tok_6oq2mixiroduzldwq4t3k2issm",
    "payment_method": "checkoutcom_card_payment",
    "quote_id": 88,
    "card_bin": 424242,
    "card_cvv": 100,
    "public_hash": "string",
    "save_card": false,
    "success_url": "http://amitbera.magentodev/ae_en/checkout_com/payment/verify",
    "failure_url": "http://amitbera.magentodev/ae_en/checkout_com/payment/fail"
  }
}
```

Also, what is the role of webhook and this failure and success  URL.

Can you please give me some information in deptah.
