### ISSUE TITLE
Module is not showing in admin and not getting installed via composer

### ISSUE THREAD

**Issue by VaseemDeveloper** [checkout/checkout-magento2-plugin#439]
I am using Magento CE 2.3.4.
I installed the module via composer but it is not showing in admin.
I can see the 2 directories created at **vendor/checkoutcom** and **vendor/checkout**
The module has created a table in DB also. But it is not showing in admin under Sales -> Payments.

When I am checking the module status, I am getting the following.
bin/magento module:enable CheckoutCom_Magento2
**Unknown module(s): 'CheckoutCom_Magento2'**

All the commands and steps following as per the steps mentioned here - https://marketplace.magento.com/media/catalog/product/checkoutcom-magento2-2-2-8-ce/user_guides.pdf

**Comment by achourey** [comment]
Hi @VaseemDeveloper 
Try following commands. 

- composer require checkoutcom/magento2:*  --no-update
- composer update checkoutcom/magento2
- php bin/magento setup:upgrade
- php bin/magento setup:di:compile 
- php bin/magento setup:static-content:deply 
- php bin/magento cache:clean

Thanks

**Comment by ved-beejadhur-cko** [comment]
Hi @VaseemDeveloper ,

I guess you have been able to install the plugin.
However, please refer to the [Readme](https://github.com/checkout/checkout-magento2-plugin#readme) doc to get the working commands for installation and update if you encounter any other issues.

Thanks
