### ISSUE TITLE
Error while installing manually

### ISSUE THREAD

**Issue by rakeshmagento** [checkout/checkout-magento2-plugin#440]
While installing manually by downloading and putting the code in **app/code**, it's giving class **CheckoutApi** not found. After doing further investigation in the code I found that the **line 20** use **\Checkout\CheckoutApi;** in file **checkout-magento2-plugin-master/Model/Service/ApiHandlerService.php.** There is no class specified on that location with the name **CheckoutApi.php**
![Screen Shot 2021-02-23 at 11 29 33 AM](https://user-images.githubusercontent.com/3923889/108813454-7b746000-75ca-11eb-9612-2c437bc1d265.png)

**Comment by alfie-loakes-cko** [comment]
@rakeshmagento When installing the plugin manually you also need to install the checkout.com PHP SDK

https://github.com/checkout/checkout-sdk-php
