### ISSUE TITLE
 Uncaught Error: Class 'Checkout\CheckoutApi' not found in /var/www/html/app/code/CheckoutCom/Magento2/Model/Service/ApiHandlerService.php:106 

### ISSUE THREAD

**Issue by tinventions** [checkout/checkout-magento2-plugin#478]
After Installing Checkout.com Extension facing  Uncaught Error: Class 'Checkout\CheckoutApi' not found in /var/www/html/app/code/CheckoutCom/Magento2/Model/Service/ApiHandlerService.php:106  issue
![Screenshot from 2021-06-11 09-30-04](https://user-images.githubusercontent.com/47660616/121628892-c2159980-ca97-11eb-84df-73ccfa54b320.png)
I have installed this module using direct download (Not with Composer)

**Comment by amitmaurya191** [comment]
You have to install CheckoutCom library files.
