### ISSUE TITLE
Address is not getting saved for first order place by new customer - apple pay

### ISSUE THREAD

**Issue by amitmaurya191** [checkout/checkout-magento2-plugin#481]
Hi,

Just found and issue on apple pay- Billing address is missing

**Scenario Step -** 

- Create a new user
- Add product to cart
- Go on checkout page
- Fill shipping address details 
- Click on billing address same as shipping address checkbox
- Select apple pay payment 
- place order

**Result** - Order successfully placed but billing address is missing on order as shown on below image. Address is not getting saved in customer account. 

**Actual Result** - Billing address should show on order detail page and also save address on customer account. 

![image](https://user-images.githubusercontent.com/59875468/123430313-a9ec6100-d5e5-11eb-8aca-728f5595b4d0.png)

**Comment by bakshivarun** [comment]
Hi @amitmaurya191,

Thanks for detailing your issue and the steps to reproduce the same. We did try to recreate this but unfortunately could not because the Billing Address was seen as expected. Could the issue be in your settings or the code? Kindly let us know. 

Best,
Varun
