### ISSUE TITLE
Change line endings to LF

### ISSUE THREAD

**Issue by roman-snitko** [checkout/checkout-magento2-plugin#49]
Not an issue, but it would be great to have **LF** EOL instead of _CRLF_

**Comment by david-fiaty-cko** [comment]
LF normalisation is now available in the dev branch. This update will be pushed to master with the next release. Please let me know any issue. Thank you.

**Comment by snowcore** [comment]
Superb! Thanks!

**Comment by david-fiaty-cko** [comment]
LF normalisation is now available in the master branch with the 1.0.22 release.
