### ISSUE TITLE
GPay does not work in checkout-magento2-plugin:2.3.1 version

### ISSUE THREAD

**Issue by VladislavSW** [checkout/checkout-magento2-plugin#490]
**Issue**
GPay does not work in checkout-magento2-plugin:2.3.1 version

**Investigation results in 2.3.1 version**
In `CheckoutCom\Magento2\Model\Ui\ConfigProvider::getConfigArray()` for the payment methods configuration the logic uses the following method `$this->config->getMethodsConfig()`, which loads configurations based on the XML configuration paths. The loader class `CheckoutCom\Magento2\Gateway\Config\Loader`, which loads configurations, uses a check in the `processGroupValues` method that checks if the configuration is hidden or not. In case if the configuration is hidden it will be skipped. 

Hidden configurations are combination of `settings/checkoutcom_configuration/fields_hidden` and `payment/checkoutcom_apple_pay/fields_hidden`. In the `checkoutcom/magento2/etc/config.xml` file for the `payment/checkoutcom_apple_pay/fields_hidden` configuration hidden fields are set to `"processing_certificate,processing_certificate_password,merchant_id_certificate,merchant_id"` by default. 

As you can see the `merchant_id` is in the hidden list by default, so it will be skipped in the configuration loader, and there will be no merchand_id configuration on the frontend, as a result, the GPay popup will not work with the missing merchandId.

**Please note** 
The above was introduced in the 2.3.1 version and is not the case for the 2.3.0 version.

**Comment by bakshivarun** [comment]
Hi @VladislavSW,

Thank you for raising your concern and apologies for not coming back to you earlier. This is an issue we have already fixed, which will be made available in the upcoming Magento 2 version release before the end of the month. 

Best,
Varun

**Comment by Dnd-Gimix** [comment]
Hello @VladislavSW ,

As this bug has already been fixed, we are closing this issue.
Feel free to open a new one if any other problem persists.

Regards,
