### ISSUE TITLE
Customize option when option type is file in product

### ISSUE THREAD

**Issue by rishigupta121** [checkout/checkout-magento2-plugin#504]
**Step to Reproduce**

1. Create a configurable product with custom option type file and the add product to cart.
2.  when we go to cart page the error comes as shown in image

**Actual result**
![image](https://user-images.githubusercontent.com/10168273/156721477-698363c8-93e3-43c6-843c-ce45fc75df16.png)

Expected Result: 

![image](https://user-images.githubusercontent.com/10168273/156722814-2cf6613f-2e8b-4347-9782-f2e455ccf59b.png)

**Comment by Dnd-Gimix** [comment]
Hello @rishigupta121 ,

Thank you for reporting this issue.

Could you provide us the Magento 2 version and the extension version you are currently using please?
Many thanks.

Regards,

**Comment by rishigupta121** [comment]
hello @Dnd-Gimix ,
magento version : 2.4.3-p1
extension version in both 2.3.4 and 3.0.0

**Comment by Dnd-Gimix** [comment]
Hello @rishigupta121 

Thank you for your feedback.

We have fixed this issue in the latest 3.0.1 version of the extension.
Can you update your extension and confirm that it is now OK?

Many thanks.
Regards,

**Comment by rishigupta121** [comment]
thanks @Dnd-Gimix this  issue is resolved in 3.0.1
I'm closing this ticket
