### ISSUE TITLE
str_contains is PHP8.0 

### ISSUE THREAD

**Issue by JamesFX2** [checkout/checkout-magento2-plugin#505]
You're using it in https://github.com/checkout/checkout-magento2-plugin/blob/0e5d5b5f59a193dc3b669f34cce99cde46bf171f/Controller/Payment/Verify.php and https://github.com/checkout/checkout-magento2-plugin/blob/0e5d5b5f59a193dc3b669f34cce99cde46bf171f/Gateway/Config/Config.php

**Comment by Dnd-Gimix** [comment]
Hello @JamesFX2 ,

Thank you for your feedback.

We have fixed the usage of the "str_contains" functions in the latest 3.0.1 version of the extension.
Can you update your extension and confirm that it is now OK?

Many thanks.
Regards,
