### ISSUE TITLE
Unable to configure module, unless

### ISSUE THREAD

**Issue by kpitn** [checkout/checkout-magento2-plugin#513]
When you install the module and go to _Setup > Configuration > Sales > Payment Method_, you can't configure the module, the button is disabled.

![disable](https://user-images.githubusercontent.com/41059/169555150-20c52d86-0afc-4252-b195-7f9d4a23483b.png)

You need to remove **disabled** mention in html console to configure module.

**Comment by Dnd-Gimix** [comment]
Hello @kpitn ,

Hope you are fine.

Can you please provide more detail on your Magento setup please:
- Magento / PHP version
- Do you have any customizations or community extension installed?
- Did you upgraded the extension to the latest version or just installed it on a fresh Magento?
- Any additional information to debug the issue

Thanks a lot!
Regards

**Comment by kpitn** [comment]
Hello @Dnd-Gimix, 

Nice to see you here

As you can see it's the last version of checkout module v4.0.0 
With Magento 2.4.4 and php 7.4.

The problem is I don't have activity_path

![activity_path](https://user-images.githubusercontent.com/41059/169565212-00af9cdf-850f-410f-b7d9-d94e6fbbf071.png)

**Comment by deepaknair3** [comment]
Facing this issue in Magento 2.4.3-p1, any solution yet?

@Dnd-Gimix please help to fix it, as this is a major issue, and not able to save configurations.

**Comment by deepaknair3** [comment]
@kpitn have you got any solution?

**Comment by kpitn** [comment]
I don't understand why payment module (not only checkout.com) want to disable the configure button.
Even more when this module override payment method selection to force checkout to appear selected by default.
https://github.com/checkout/checkout-magento2-plugin/blob/master/view/frontend/web/js/model/checkout-data-resolver.js



1 - Quick solution : Right Click > Inspect and remove disabled from dom.
2 - Lasting solution : Override the block with a preference or a plugin on the _isPaymentEnabled function with "return true"

Strange name for this function _isPaymentEnabled (underscore mean old magento private method name) and the scope is public ?

**Comment by Dnd-Gimix** [comment]
Hello @deepaknair3 @kpitn ,

Thank you both for the feedback.

It seems that there is currently an issue when the "Paypal" module is disabled, causing the Checkout "Configure" button to disappear.

Can you confirm that you both disabled the native "Paypal" extension?
While we proceed to fix this issue, could you maybe re-enable the extension to prevent this behavior?

Thank you.
Regards,

**Comment by kpitn** [comment]
Hi @Dnd-Gimix , 
You are right paypal module is disable in my store

**Comment by deepaknair3** [comment]
Hi @Dnd-Gimix ,
Yes, paypal modules are disabled.

**Comment by Dnd-Gimix** [comment]
Hello @kpitn @deepaknair3 ,

Thank you for the confirmation.
I confirm to you that a new release at the end of the month will contain a bug fix for this issue.

Have a good day.
Regards,

**Comment by deepaknair3** [comment]
Hello @Dnd-Gimix ,

When we can expect a new release with this fix.

Thanks

**Comment by dio5** [comment]
On Magento. 2.4.2-p1 we have similar issues, even with paypal enabled. 

The configure button is enabled but getting JS errors in both Chrome and FF, though different ones and the behaviour is different but comes down to being unable to save or click/open anything (not only just the checkoutcom parts).

This happens with 4.0.0, wasn't happening with the previous version.

JS errors vary from 

Uncaught ReferenceError: ckoToggleSolution is not defined

to

Uncaught TypeError: Cannot set properties of undefined (setting 'innerText')
    at processABC ((index):6032:52)
    at checkService ((index):6046:13)

**Comment by Dnd-Gimix** [comment]
Hello @kpitn @deepaknair3 @dio5 ,

The fix for Paypal module disabled causing the configuration to disappear has been released in the latest version of the extension : [4.1.1](https://github.com/checkout/checkout-magento2-plugin/releases/tag/4.1.1)

Can you please upgrade and try again?

Many thanks.
Regards,

**Comment by kpitn** [comment]
It's ok for me with last version

**Comment by Dnd-Gimix** [comment]
Great, thank you @kpitn for the feedback, let's close this issue then!
Have a good day.
Regards,
