### ISSUE TITLE
Apple Pay script needs to check if client SUPPORTS v14

### ISSUE THREAD

**Issue by JamesFX2** [checkout/checkout-magento2-plugin#542]
You added 

                                var session = new ApplePaySession(14, paymentRequest);

in release 5.0 but you're not checking if the current client supports v14, just whether or not they `canMakePaymentsWithActiveCard`

Users are getting silent errors in their browser when they click place order. Just add a check for whether they support that version. 

https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778014-supportsversion

https://github.com/checkout/checkout-magento2-plugin/blob/master/view/frontend/web/js/view/payment/method-renderer/checkoutcom_apple_pay.js#L210-L212

Thanks.

**Comment by JamesFX2** [comment]
Also, why version 14? The cart page uses the more widely supported 12.

**Comment by DnD-Behou** [comment]
Hi @JamesFX2 
Issue has been solved in the latest releases we are using version 14 and if not supported, version 5 is used.
Thanks for your contribution

**Comment by JamesFX2** [comment]
@DnD-Behou are you serious?

https://github.com/checkout/checkout-magento2-plugin/blob/master/view/frontend/web/js/view/payment/cart/checkoutcom_applepay_cart.js was updated. This relates your verson of Apple Pay Checkout. 

The version for the payment method on the checkout is https://github.com/checkout/checkout-magento2-plugin/blob/master/view/frontend/web/js/view/payment/method-renderer/checkoutcom_apple_pay.js wasn't. 

![image](https://github.com/checkout/checkout-magento2-plugin/assets/8654869/49ac0b5a-b62a-477b-be09-ee4d6147c36e)

Est-ce que cela aiderait si nous communiquions en français? Ou payez-moi de l'argent et je réparerai votre extension parce que j'en ai marre de cette situation.

Nous avons embauché une société de tests et c’est l’un des problèmes signalés. Ils ont dit à mes patrons que cette erreur leur coûtait 250 000 euros par an, ou quelque chose de ridicule. Sais-tu à quel point cela me fait paraître incompétent ? J'ai corrigé votre extension plus de 30 fois, principalement avec des composer patches car je ne m'attends pas à ce que vous les corrigiez, mais parfois je suis persuadé de créer des tickets afin que les autres puissent voir pourquoi leurs taux de conversion ont chuté.

Mon erreur préférée était lorsque vous empêchiez le paiement pour les nouveaux clients et les clients invités parce que votre développeur avec 1 an d'expérience PHP que vous aviez autorisé à soumettre du code ne comprenait pas comment searchcriteria / repositories fonctionnait et ajoutait du code qui signifiait que toutes les transactions étaient chargé en arrière-plan.
