### ISSUE TITLE
Issue on frontend side on Magento Commerce 2.x

### ISSUE THREAD

**Issue by elvinristi** [checkout/checkout-magento2-plugin#55]
Didn't start to send it as PR but wanted to raise the issue which exists in current module.

(1) Changes, how we use in our module so there wouldn't be conflicting overrides with `view/frontend/layout/sales_*` files:

- vaimo/checkoutcom-magento2-plugin@2a80dcecdaa94ba68878dcd2451dff28cf58cc89

Issue is that current module is redefining blocks in layout files and resetting core's already defined blocks and loosing some Commerce specific definitions.

(2) Also when using other payment options in project then due `CheckoutCom\Magento2\Block\Order\Info::getPaymentInfoHtml` brings in abnormal behavior.

**Comment by david-fiaty-cko** [comment]
Hi Elvin,

You have already raised this issue in a PR here in December 2017: https://github.com/checkout/checkout-magento2-plugin/pull/37

As explained in the comment, we cannot remove the override for the moment as it covers requirements expressed by multiple stakeholders. Your request will be satisfied in the scope of a refactoring of the module. 

The release of the refactored module was planned for January but we had to postpone for internal reasons. I will keep you updated as soon as the release you are expecting is available.

Thank you

**Comment by elvinristi** [comment]
great! forgot already about #37 :)
