### ISSUE TITLE
Can't use the plugin in production mode

### ISSUE THREAD

**Issue by navidnadali** [checkout/checkout-magento2-plugin#58]
Hi there,

We are unable to use the latest version in Production Mode: 

`2018/05/23 13:38:55 [error] 19510#19510: *28 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Source class "\CheckoutComTransfer" for "CheckoutComTransferFactory" generation does not exist. in /mnt/volume-lon1-01/var/www/vhosts/m2.s.vortexcommerce.com/htdocs/amritanutrition/releases/cb69778d3ea99fa2e44d6ccab90020b7049f61e3/vendor/magento/framework/Code/Generator.php:185
Stack trace:
#0 /mnt/volume-lon1-01/var/www/vhosts/m2.s.vortexcommerce.com/htdocs/amritanutrition/releases/cb69778d3ea99fa2e44d6ccab90020b7049f61e3/vendor/magento/framework/Code/Generator.php(112): Magento\Framework\Code\Generator->tryToLoadSourceClass('CheckoutComTran...', Object(Magento\Framework\ObjectManager\Code\Generator\Factory))
#1 /mnt/volume-lon1-01/var/www/vhosts/m2.s.vortexcommerce.com/htdocs/amritanutrition/releases/cb69778d3ea99fa2e44d6ccab90020b7049f61e3/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('CheckoutComTran...')
#2 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Chec" while reading response header from upstream, client: 10.131.66.73, server: ~^(?<subdomain>.+)\.(?<platform>[(m2).]+)\.(?<environment>[(s|d|p).]+)\.vortexcommerce.com, request: "GET /?fsd HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "amritanutrition.m2.s.vortexcommerce.com"
2018/05/23 13:39:01 [error] 19510#19510: *28 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Source class "\CheckoutComTransfer" for "CheckoutComTransferFactory" generation does not exist. in /mnt/volume-lon1-01/var/www/vhosts/m2.s.vortexcommerce.com/htdocs/amritanutrition/releases/cb69778d3ea99fa2e44d6ccab90020b7049f61e3/vendor/magento/framework/Code/Generator.php:185
Stack trace:
#0 /mnt/volume-lon1-01/var/www/vhosts/m2.s.vortexcommerce.com/htdocs/amritanutrition/releases/cb69778d3ea99fa2e44d6ccab90020b7049f61e3/vendor/magento/framework/Code/Generator.php(112): Magento\Framework\Code\Generator->tryToLoadSourceClass('CheckoutComTran...', Object(Magento\Framework\ObjectManager\Code\Generator\Factory))
#1 /mnt/volume-lon1-01/var/www/vhosts/m2.s.vortexcommerce.com/htdocs/amritanutrition/releases/cb69778d3ea99fa2e44d6ccab90020b7049f61e3/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('CheckoutComTran...')
#2 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Chec" while reading response header from upstream, client: 10.131.66.73, server: ~^(?<subdomain>.+)\.(?<platform>[(m2).]+)\.(?<environment>[(s|d|p).]+)\.vortexcommerce.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "amritanutrition.m2.s.vortexcommerce.com"`

**Comment by david-fiaty-cko** [comment]
Hi Navid, please confirm if you can see this file in the module: Gateway\Http\TransferFactory.php
Also please provide your Magento version, the module version and your PHP version.

**Comment by navidnadali** [comment]
Hi David,

Thank you for your fast reply. 

Our M2 version: 2.2.3

Yes, I can see as follow: 

`web@s:~/m2.s.vortexcommerce.com/htdocs/amritanutrition/live$ ls -la vendor/checkoutcom/magento2/Gateway/Http/TransferFactory.php 
-rw-rw-r-- 1 web web 1829 May 23 13:34 vendor/checkoutcom/magento2/Gateway/Http/TransferFactory.php`

`web@s:~/m2.s.vortexcommerce.com/htdocs/amritanutrition/live$ md5sum vendor/checkoutcom/magento2/Gateway/Http/TransferFactory.php 
9b3d210589cde4a666f623f23c231796  vendor/checkoutcom/magento2/Gateway/Http/TransferFactory.php
web@s:~/m2.s.vortexcommerce.com/htdocs/amritanutrition/live$ `

Please can you let me know if you have any idea? I'm still trying to debug with no luck so far

**Comment by navidnadali** [comment]
Hi @david-fiaty-cko ,

Sorry our PHP version as well: PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

Please let me know if you need anything else from me at all

**Comment by david-fiaty-cko** [comment]
Magento 2 generates Factory classes inside var/generation directory. So, if there is a folder permission issue or a folder owner issue with that directory then the factory class cannot be generated and you can get this kind of errors.

Please check the following points:
1- That all files have 644 permissions 
2- That all folders have 755 permissions
3- That the web server is the owner for all M2 files and folders
4- Then try recompiling the install

**Comment by navidnadali** [comment]
Hi David,

I'm very sorry about that - PHPFPM had the path cached (we mount the var directory) so it can be reused between deployments, I had checked everything but somehow forgot about that, your comment immediately pointed me to this.

Thank you again and my apologies for wasting your time,

All the best,
Navid

**Comment by david-fiaty-cko** [comment]
No worries Navid, anytime.
