### ISSUE TITLE
Impossible to place an order with enabled terms and conditions (hosted)

### ISSUE THREAD

**Issue by roman-snitko** [checkout/checkout-magento2-plugin#64]
## Prerequisites: ##
 - Magento Open Source: 2.2.3
 - Checkoutcom module: latest version 1.0.26
 - Checkoutcom integration type: **Hosted**

## Steps to reproduce: ##
 - Enable terms and conditions in admin area
 - Add new conditions in admin (with manual type)
 - Go to frontend and try to place an order
 - After entering card details on the checkout.com site it redirects back to Magento cart with this error message: "**Please agree to all the terms and conditions before placing the order.**"

**Comment by nicolas-maalouf-cko** [comment]
Hi @roman-snitko-vaimo 
This is due to a Magento core bug that was introduced in version 2.2.2 and that was fixed in 2.2.4 

Can you try updating and see if the problem is resolved?

**Comment by roman-snitko** [comment]
Unfortunately, we can't do upgrade.
Moreover, we have this issue on another installation with older Magento version: 2.1.9

**Comment by brucemead** [comment]
Hi @roman-snitko-vaimo, long time no speak, hope you're well?!

To confirm we're seeing this issue on `2.2.4` as well.

**Comment by nicolas-maalouf-cko** [comment]
My bad, it seems to be there from earlier versions too.
Here's the link to the Magento repo Github issue:
https://github.com/magento/magento2/issues/11885

**Comment by nicolas-maalouf-cko** [comment]
@roman-snitko-vaimo this has been fixed in release 1.0.27 for the Hosted solution and was tested successfully on 2.2.3.
Can you please update and see if it works on your end too?

@brucemead is this happening with the Hosted or the Frames solution on your end?

**Comment by brucemead** [comment]
Hi @nicolas-maalouf-cko, we're not seeing it working in Frames, I can't say we've checked Hosted though.

**Comment by roman-snitko** [comment]
@nicolas-maalouf-cko thank you for implementing workaround.
