### ISSUE TITLE
Place order button is disabled after leaving checkout and returning back

### ISSUE THREAD

**Issue by undefined-olha** [checkout/checkout-magento2-plugin#67]
Checked on clean Magento 2.1.9.
Checkout com module version: 1.0.23.3

### Precondition 
- Frames solution enabled
- More then one payment method is available

### Steps to replicate
1. Add some items to cart
2. Go to Checkout as Guest
3. Fill out shipping info
4. Go to Step 2 of checkout
5. Select “Cash on Delivery” payment method
6. Leave checkout (you can go to shopping bag, for example)
7. Go to checkout again
8. Go to Step 2 of checkout
9. Payment method is preselected

### Expected
Place order button is enabled

### Actual
Place order button is disabled

### Note
* Button gets enabled again after switching payment methods

![screen shot 2018-07-02 at 6 26 43 pm](https://user-images.githubusercontent.com/15153675/42172798-c29d47b6-7e25-11e8-8d21-61f036df191e.png)

**Comment by david-fiaty-cko** [comment]
@olgalytvynenko, thank you for reporting this. We have been able to reproduce the issue. There should be a release by Wednesday that fixes it.

**Comment by david-fiaty-cko** [comment]
Issue fixed in the latest 1.0.29 release.
