### ISSUE TITLE
Quote addresses are empty after failed card authorization

### ISSUE THREAD

**Issue by snowcore** [checkout/checkout-magento2-plugin#73]
### Prerequisites
- Vanilla Magento installation (2.2.3)
- Latest checkoutcom module (1.0.30) configured to use **Frames** (sandbox mode)

### Steps to reproduce
1. Go to checkout with some products in cart
2. Fill in shipping address, proceed to payment step
3. Enter correct credit card number, but invalid CVV code, hit "Place Order"
4. Error message appears (Authorization failed)
5. Reload the page
6. Addresses are empty (see a screenshot)
![checkoutcomemptyaddress](https://user-images.githubusercontent.com/933169/43968285-580680f2-9ccf-11e8-8ee9-d836a18315af.png)

**Comment by david-fiaty-cko** [comment]
This seems to be a Magento 2 issue.
See 
https://magento.stackexchange.com/questions/148454/shipping-address-missing-on-payment-page-refresh
or
https://github.com/magento/magento2/issues/6817

**Comment by david-fiaty-cko** [comment]
The issue doesn't seem to be fixed in the version 2.2.3 you are using. Please consider upgrading.
