### ISSUE TITLE
Order status problem

### ISSUE THREAD

**Issue by sweethurricane7** [checkout/checkout-magento2-plugin#77]
Hi,

Seems like there is an issue with "Authorization order status" setting.
By default it equals to **Pending Payment**, but in fact, the order status is always **Processing** after authorization.

Tested with the latest checkoutcom module on Magento 2.2.5

**Comment by nicolas-maalouf-cko** [comment]
Hi @sweethurricane7 

What integration mode are you using? Frames or Hosted? and are you testing with 3D Secure?

Have you configured the redirection and webhook URLs on your Checkout.com hub dashboard with the links provided in the plugin settings?

Thanks

**Comment by irfanlateef-visionet** [comment]
Hi Nocolas,

I put your module in app/code/CheckoutCom/Magento2 and executed following commands

`php bin/magento setup:upgrade
php bin/magento cache:flush
php bin/magento cache:clean`

Also, I checked admin configuration in Stores > Configuration > Sales > Payment Methods > Checkout.com it is showing well. But Hosted checkout payment method isn't showing on front end. Can you please help me in this regards. I have to integrate hosted checkout but it is not showing on front end.
I am using Magento ver. 2.2.4

Thanks,

Irfan Lateef

**Comment by irfanlateef-visionet** [comment]
I have tried to install your module via composer but it is showing empty screen on front end and backend was throwing exception:

`PHP Fatal error:  Uncaught Error: Call to a member function setActive() on boolean in C:\xampp\htdocs\khaadi2\vendor\magento\module-backend\Model\View\Result\Page.php:27`

**Comment by nicolas-maalouf-cko** [comment]
Have you saved the different API keys in the configuration panel of the plugin?

Also are you running Magento2 on Windows?
Please have a look at this thread if it's the case:
https://github.com/magento/magento2/issues/13504

**Comment by irfanlateef-visionet** [comment]
I don't have any key. I just received merchant id, operator id and password. What should I enter in Public Key, Secret Key and Private Shared Key.

Can you please help me in this regards.

**Comment by nicolas-maalouf-cko** [comment]
Where did you get the details from? Are you sure it's from Checkout.com?

In all cases you can get a Sandbox account by using the "Get test account" button found here:
https://www.checkout.com/

**Comment by sweethurricane7** [comment]
We use **Hosted** integration, no 3D Secure.
Webhooks are configured properly (we log all incoming requests from Checkout.com)
Magento 2 instance is running on Ubuntu.
This is happening in the production mode.

**Comment by nicolas-maalouf-cko** [comment]
hi @sweethurricane7 can you please list the different order statuses configured in the plugin?
(New order status etc...)

Thanks

**Comment by sweethurricane7** [comment]
Here they are:

<img width="756" alt="checkoutcom-order-status" src="https://user-images.githubusercontent.com/36376477/46600722-c1145900-caf3-11e8-84b6-6a5ee7e17c38.png">

**Comment by nicolas-maalouf-cko** [comment]
Hi @sweethurricane7,

Can you please provide your Sandbox account name so we can check the test transactions on our end? 

Thank you

**Comment by david-fiaty-cko** [comment]
@sweethurricane7, this looks like an issue in the module. It's picking the default store value when it should pick specific store values. We are working on a module update that will be released by the end of the week. You will be notified in this thread as soon as the update is available.

**Comment by david-fiaty-cko** [comment]
This issue should be fixed on the latest release 1.0.34. Please reopen if needed.
