### ISSUE TITLE
Cannot checkout if keys are not validated, even when disabled

### ISSUE THREAD

**Issue by maderlock** [checkout/checkout-magento2-plugin#8]
With 1.0.6 installed, **even if the extension is not enabled**, if I do not have correct keys entered then when I visit https://somedomain.com/checkout/cart/ instead of the cart I get to see this:

	1 exception(s):
	Exception #0 (CheckoutCom\Magento2\Gateway\Exception\ApiClientException): Your API key is invalid.

	Exception #0 (CheckoutCom\Magento2\Gateway\Exception\ApiClientException): Your API key is invalid.
	#0 .../vendor/checkoutcom/magento2/Model/Ui/ConfigProvider.php(109): CheckoutCom\Magento2\Model\Service\PaymentTokenService->getToken()
	#1 .../vendor/checkoutcom/magento2/Model/Ui/ConfigProvider.php(91): CheckoutCom\Magento2\Model\Ui\ConfigProvider->getPaymentToken()
	#2 .../vendor/magento/module-checkout/Model/CompositeConfigProvider.php(32): CheckoutCom\Magento2\Model\Ui\ConfigProvider->getConfig()
	#3 .../vendor/magento/module-checkout/Block/Cart/Shipping.php(54): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
	#4 .../var/generation/Magento/Checkout/Block/Cart/Shipping/Interceptor.php(24): Magento\Checkout\Block\Cart\Shipping->getCheckoutConfig()
	#5 .../vendor/magento/module-checkout/view/frontend/templates/cart/shipping.phtml(28): Magento\Checkout\Block\Cart\Shipping\Interceptor->getCheckoutConfig()
	#6 .../vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/Volumes/Sites/...')
	#7 .../vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Cart\Shipping\Interceptor), '/Volumes/Sites/...', Array)
	#8 .../vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Element\Template->fetchView('/Volumes/Sites/...')
	#9 .../var/generation/Magento/Checkout/Block/Cart/Shipping/Interceptor.php(221): Magento\Checkout\Block\Cart\Shipping\Interceptor->___callPlugins('fetchView', Array, Array)
	#10 .../vendor/magento/framework/View/Element/Template.php(279): Magento\Checkout\Block\Cart\Shipping\Interceptor->fetchView('/Volumes/Sites/...')
	#11 .../vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
	#12 .../vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Element\AbstractBlock->toHtml()
	#13 .../var/generation/Magento/Checkout/Block/Cart/Shipping/Interceptor.php(520): Magento\Checkout\Block\Cart\Shipping\Interceptor->___callPlugins('toHtml', Array, Array)
	#14 .../vendor/magento/framework/View/Layout.php(542): Magento\Checkout\Block\Cart\Shipping\Interceptor->toHtml()
	#15 .../vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('checkout.cart.s...')
	#16 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart.s...')
	#17 .../vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.cart.s...')
	#18 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.cart.s...', true)
	#19 .../vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.cart.s...')
	#20 .../vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('cart.summary')
	#21 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('cart.summary')
	#22 .../vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('cart.summary')
	#23 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('cart.summary', true)
	#24 .../vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('cart.summary')
	#25 .../vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('cart.sidebar.wi...')
	#26 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('cart.sidebar.wi...')
	#27 .../vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('cart.sidebar.wi...')
	#28 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('cart.sidebar.wi...', true)
	#29 .../vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement('cart.sidebar.wi...', true)
	#30 .../var/generation/Magento/Checkout/Block/Cart/Interceptor.php(557): Magento\Framework\View\Element\AbstractBlock->getChildHtml('with-items', true)
	#31 .../vendor/magento/module-checkout/view/frontend/templates/cart.phtml(15): Magento\Checkout\Block\Cart\Interceptor->getChildHtml('with-items')
	#32 .../vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/Volumes/Sites/...')
	#33 .../vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Cart\Interceptor), '/Volumes/Sites/...', Array)
	#34 .../vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Element\Template->fetchView('/Volumes/Sites/...')
	#35 .../var/generation/Magento/Checkout/Block/Cart/Interceptor.php(325): Magento\Checkout\Block\Cart\Interceptor->___callPlugins('fetchView', Array, Array)
	#36 .../vendor/magento/framework/View/Element/Template.php(279): Magento\Checkout\Block\Cart\Interceptor->fetchView('/Volumes/Sites/...')
	#37 .../vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
	#38 .../vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Element\AbstractBlock->toHtml()
	#39 .../var/generation/Magento/Checkout/Block/Cart/Interceptor.php(650): Magento\Checkout\Block\Cart\Interceptor->___callPlugins('toHtml', Array, Array)
	#40 .../vendor/magento/framework/View/Layout.php(542): Magento\Checkout\Block\Cart\Interceptor->toHtml()
	#41 .../vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('cart.sidebar.wi...')
	#42 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('cart.sidebar.wi...')
	#43 .../vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('cart.sidebar.wi...')
	#44 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('cart.sidebar.wi...', true)
	#45 .../vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('cart.sidebar.wi...')
	#46 .../vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('sidebar.main')
	#47 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sidebar.main')
	#48 .../vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sidebar.main')
	#49 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sidebar.main', true)
	#50 .../vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('sidebar.main')
	#51 .../vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('div.sidebar.mai...')
	#52 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('div.sidebar.mai...')
	#53 .../vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('div.sidebar.mai...')
	#54 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('div.sidebar.mai...', true)
	#55 .../vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('div.sidebar.mai...')
	#56 .../vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
	#57 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
	#58 .../vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
	#59 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
	#60 .../vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
	#61 .../vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
	#62 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
	#63 .../vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
	#64 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
	#65 .../vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
	#66 .../vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
	#67 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
	#68 .../vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
	#69 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
	#70 .../vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
	#71 .../vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
	#72 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
	#73 .../vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
	#74 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
	#75 .../vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
	#76 .../vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
	#77 .../var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
	#78 .../vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
	#79 .../vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
	#80 .../vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
	#81 .../vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
	#82 .../vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
	#83 .../vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
	#84 .../vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
	#85 .../vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
	#86 .../vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
	#87 .../vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
	#88 .../var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
	#89 .../vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
	#90 .../vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
	#91 .../pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
	#92 {main}

It would be helpful if the extension just did not present itself as a payment option instead of throwing this as an uncaught error on the frontend. Indeed, when not enabled it should not really be doing any checks at all!

**Comment by nicolas-maalouf-cko** [comment]
Hi @maderlock ,

Thanks for reporting the issue, we'll be fixing it and providing an update.

Meanwhile please let us know if you're able to properly use the extension with keys set.

Thanks

**Comment by maderlock** [comment]
Yes - that has not changed. With the keys entered it works fine :)

**Comment by nicolas-maalouf-cko** [comment]
Closing the issue as it has been resolved in the latest release
