### ISSUE TITLE
Generic styling added to body

### ISSUE THREAD

**Issue by Danielc3** [checkout/checkout-magento2-plugin#9]
Below is the CSS that this module appears to be appending to the body:

`
	html {
	    overflow: -moz-scrollbars-vertical !important; 
	    overflow-y: scroll !important;
	}

	body {
	    overflow: visible !important;
	}

	#embeddedForm {
		z-index: 0 !important;
	}
	
	#embeddedForm, #embeddedForm iframe {
	    position: relative !important;
	}

	#embeddedForm iframe {
		min-height: 153px;
	}

	#cko-form-holder {
	    max-width: 50%;
	}
`

The overflow: visible !important is breaking some styling on the site we are trying to use this extension on. Could this please be made more specific?

**Comment by maderlock** [comment]
I can see that this has been addressed in 1.0.7 for the frontend. Could you please do the same with checkoutcom/magento2/view/adminhtml/templates/embedded.phtml ?

**Comment by david-fiaty-cko** [comment]
issue fixed in new version 1.0.8

**Comment by david-fiaty-cko** [comment]
Complementary changes added in version 1.0.9
