### ISSUE TITLE
Code stye doesn't follow MEQP coding standartd

### ISSUE THREAD

**Issue by likemusic** [checkout/checkout-magento2-plugin#93]
It would be creat to reformat code according to [MEQP Coding Standard](https://github.com/magento/marketplace-eqp).

**Comment by david-fiaty-cko** [comment]
Thank you for the comment. We are working on a release that will follow the MEQP Standard. You will be informed as soon as it's out.

**Comment by likemusic** [comment]
@david-fiaty-cko wy not keep this issue opened until it will be fixed?

**Comment by david-fiaty-cko** [comment]
We are working on a new release completely redesigned for the new Checkout.com gateway. The MEQP Standard will be taken in account for the new series. Not for the series available now. 
If it can help I have added a "won't fix" label to the issue. Thank you.

**Comment by david-fiaty-cko** [comment]
@likemusic, please have a look at the new plugin version 2.0.4 on the master branch, it follows the MEQP standard and is also available on the market place.
