### ISSUE TITLE
Saved card vault title not showing

### ISSUE THREAD

**Issue by joe-vortex** [checkout/checkout-magento2-plugin#98]
## Issue
Saved cards don't show the vault title set in system config under `payment/checkout_com_cc_vault/title` on https://github.com/checkout/checkout-magento2-plugin/blob/master/Gateway/Config/Config.php#L218

## Solutions
This can be fixed by either:
- Setting the payment method code within this class before the return statement: `        $this->setMethodCode('checkout_com_cc_vault');` and changing the value string to just `title`
- Using scope config directly: ```return (string) $this->scopeConfig->getValue(
            'payment/checkout_com_cc_vault/title',
            ScopeInterface::SCOPE_STORES,
            $this->storeManager->getStore()
        );```

## System
Core version: 2.2.7
Module version: 1.0.40

## Actions to replicate
- login as a customer
- place a test order with checkoutcom (checking save card option)
- place another test order

## Result
Vault title for saved card does not show resulting in "   ending XXXX..."

## Side notes:
Composer php requirements need to be updated for Magento 2.2+. They are currently:
`php: ~5.5.0|~5.6.0|~7.0` and should be `php: ~7.0|~7.1|~7.2` to be inline with Magento system requirements. Please see https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html#php
The composer option `--ignore-platform-reqs` has to be used to install the extension on systems running non-deprecated php versions (7.1 or greater)

**Comment by david-fiaty-cko** [comment]
@joe-vortex, thank you for your comments. A new release 1.0.44 is available with the relevant changes.

**Comment by joe-vortex** [comment]
@david-fiaty-cko Thanks very much for that! I'd made a patch for the project I was working on but can just update the module version now. I'll let you know if I find any other bugs :slightly_smiling_face:
